name: Hugo Publish

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.70.0'
        extended: true

    - name: Build
      run: |
        cd src
        hugo

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        keep_files: true
        publish_dir: /tmp/site
        publish_branch: master
        commit_message: Update site ${{ steps.date.outputs.date }}
